### ISSUE TITLE
AltGr "locks" for some time

### ISSUE THREAD

**Issue by yassintp** [andischerer/atom-keyboard-localization#125] opened 2016-04-06 13:49 UTC
I am using the package keyboard-localization with the current Atom version 1.6.2 and the German keymap de_DE. In principle, it works great as I am used to typing AltGr-Q for @ insteand of Ctrl-Alt-Q and so on, however, using the AltGr key makes it "locked in" for some time (1-2 minutes), causing the "e" key to write a €, "q" to write a @ and so on. 

The problem is not with my key actually locking, but restricted to Atom and/or the package. I already tried saving, pressing AltGr again, using a Ctrl-Alt- shortcut and so on to try to "reset" the key, but this doesn't work - it seems to really be a time-based reset. 

I would be happy to provide more information to help solving the issue. 

EDIT: Figured out there are already #110 and #115 describing the same problem. However, I am already using the latest version 1.4.18 where it should be fixed and I am on Atom 1.6.2 which shouldn't be affected at all, right?

**Comment by ligustah** [comment] 2016-04-09 20:52
I am on de_DE as well and also experience this issue. I am using the most recent versions respectively. It's especially annoying because I use `AltGr` to add curly brackets in C-style languages.

Pressing `Alt + Tab` twice (thus changing to another window and back to Atom) removes the lock for me.

**Comment by gdlx** [comment] 2016-04-13 08:05
Same issue with fr_FR. Same workaround than @ligustah.
The issue appeared to me after moving to beta 1.7. Not sure if I've upgraded `atom-keyboard-localization` at the same time.
Anyway, disabling the package resolves the issue, but I need it ;o)

EDIT: My mistake, I was using 1.4.16. 1.4.18 seems ok.

**Comment by manuelbieh** [comment] 2016-04-14 12:12
Same here. After updating to Atom 1.7.0 and keyboard-localization to 1.4.18 my AltGr key seems to be locked. Everytime I just type "e" I get an € symbol, everytime I press "q" i get an @

**Comment by cladewig** [comment] 2016-04-14 12:32
Same Here. AltGr stucked. Can be unstucked by pressing Alt+Tab or focus diffrent window.

**Comment by ligustah** [comment] 2016-04-14 12:49
I think my Atom just updated to 1.7. I cannot currently reproduce the original issue (1.4.18, de_DE).

**Comment by cladewig** [comment] 2016-04-14 13:01
Atom 1.7 (Package is 1.4.18, de_DE) here. 
Problem still exists. Just pressing `AltGr`and it's locked. `AltGr + Q` and `q` becomes `@` everytime. `Ctrl + Alt + Q` and no problem. So just `AltGr`.

**Comment by PhiLhoSoft** [comment] 2016-04-14 14:07
I have the issue after restarting Atom, which upgraded it from 1.6.2 to 1.7.0. I hadn't the problem before. Version was 1.4.16, I upgraded to 1.4.18, and still have the same problem.
French (fr_FR) keyboard.
Not sure how to help you debugging the issue.

**Comment by va-dim** [comment] 2016-04-14 14:23
same here on 1.4.16 running DE layout @atom 1.7

**Comment by manuelbieh** [comment] 2016-04-14 14:33
I "fixed" it. Or at least I found a way to solve the problem. What I did was:
- download the 1.4.14 release zipfile
- unzip it to `atom/packages/keyboard-localization` and overwrite all existing files
- restart Atom
- it now worked!
- then download the 1.4.18 release **zipfile**
- unzip it to `atom/packages/keyboard-localization` folder and overwrite all existing files again
- restart Atom
- it still works!

Maybe it already works if you download the 1.4.18 zipfile instead of using the Atom Package Manager to update it but the way I described above worked!

Oh and by the way: I first downgraded to 1.4.16 using the zipfile download and still had the problem. So something magical obviously happened after I downgraded to 1.4.14.

**Comment by cladewig** [comment] 2016-04-14 15:19
@manuelbieh thx...working for me.

**Comment by andischerer** [comment] 2016-04-14 16:06
To clear things up, if you're on atom 1.7 you have to upgrade keyboard-localization to 1.4.18 for a working altgr key. 
I cant reproduce a locking altgr with this configuration. Could be an incomplete package update issue. Have you tried installing keyboard-localization via commanline ?

**Comment by PhiLhoSoft** [comment] 2016-04-15 08:09
Following @andischerer's advice, I uninstalled keyboard-localization from Atom. I had an error telling it couldn't uninstall it, but I found out that the package folder was effectively removed. I am on Windows 7, I often get random folder locks, that's might be one of these glitches.

Anyway, I closed Atom, then started it again. I installed 1.4.18 again (from Atom). And, voilà! I can type [ { '' } ] again... :smile: :fireworks: 

BTW, @andischerer, thanks for this fine package, very useful. I hope someday the Atom team will just integrate this functionality in Atom (they don't seem in a hurry...).

**Comment by pinki3** [comment] 2016-04-21 11:19
Same issue for sv_SE!

**Comment by PhiLhoSoft** [comment] 2016-04-21 11:23
@pinki3 Your report is a bit short... What version of Atom? Of package? What system? Have you tried the fixes described above?

**Comment by pinki3** [comment] 2016-04-21 11:36
@PhiLhoSoft Atom couldn't update the package due to my company proxy, was stuck on v1.4.16. Upgraded to version 1.4.18 via another connection and **it's now working fine with sv_SE**. Sorry for posting crap :grin:

Mark issue as resolved?

**Comment by colin-kiegel** [comment] 2016-04-26 13:45
manually removing and re-installing the package v1.4.18 solved this issue for me.

**Comment by Bosek** [comment] 2016-05-13 14:11
OMG thank you for the "fix"! It was driving me crazy. My life is complete again.

**Comment by AttilaSATAN** [comment] 2016-05-25 20:17
As @manuelbieh mentioned donwloading the 1.4.18 release solves the problem. You don't need to downgrade the package. Just download the release and unzip to the package directory. By the way thank you Manuel.

**Comment by Lordmau5** [comment] 2016-08-01 10:56
Tried this an hour ago when I was still at home but it didn't work.

Using the newest beta of Atom (which was 1.9.0-beta0 iirc?) and 1.4.18 of keyboard-localization.

**Comment by andischerer** [comment] 2016-09-23 09:08
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)

**Closed as completed by andischerer** 2016-09-23 09:08 UTC

**Comment by manny647** [comment] 2017-10-25 12:58
Do the following characters show up ^çàèé¨ÀÇ instead of []{}\|"?

Fix for Special Character Lock / Altgr / Alt gr issue:

On my keyboard I was able to resolve the matter by pressing the left "shift + ctrl keys" at the same time. After I released them I tested and the special character lock was reversed.

Give it a shot! Hope it works for you.
