### ISSUE TITLE
Brazilian Keymap not working

### ISSUE THREAD

**Issue by ghost** [andischerer/atom-keyboard-localization#48] opened 2015-08-05 04:32 UTC
Unfortunatelly the Br Keybmap is not working and my personal generated keymap isn't saving as it's supposed to be.
Every time I open the editor I have to use the Keyboard Localization to update my keymap. It seems to just ignore my Keymap file.

**Comment by andischerer** [comment] 2015-08-08 12:47
Could you please give more details on what's not working ?
When you open atom, is there any logmessage from keyboard-localization package in the devtools console ?

**Comment by ghost** [comment] 2015-08-08 13:17
Of course I can give you more deatils, sorry if I haven't been so clear.
I installed the keyboard-localization package and followed the instructions on github page.
If I choose the pt-BR keymap, my keyboad still working with the same wrong configuration.
If I create my own keymap and save it as the instructions tell me to do it works a little and after some time it stops and the and the old configuration are automatically activated.
The only way to properly use all the keys of my pt-BR keyboard is keeping the "Key-map Generator" tab open all the time.

**Comment by andischerer** [comment] 2016-02-24 18:55
duplicate of #108

**Closed as completed by andischerer** 2016-02-24 18:55 UTC
