### ISSUE TITLE
fr_FR - Linux - Same keyCode sent for different keys

### ISSUE THREAD

**Issue by benoitvidis** [andischerer/atom-keyboard-localization#37] opened 2015-07-01 10:35 UTC
It looks like the package only listens to the keyDown event.

Can be reproduced in the browser console:

```
onkeydown = function(e) { console.log(e); }
```

Pressing '<' and '*' return the same keyEvent, with the same keyCode (220) and the same keyIdentifier (U+00DC).

The only way to differentiate the keys seems to be to use the onkeypress event.

**Comment by andischerer** [comment] 2015-07-06 16:51
duplicate of #19

**Comment by andischerer** [comment] 2015-08-08 12:38
should be fixed in v1.4.7

**Closed as completed by andischerer** 2015-08-08 12:38 UTC
Labels: duplicate
