### ISSUE TITLE
AltGr-Key and shift+number doesn't work in french layout

### ISSUE THREAD

**Issue by KabbAmine** [andischerer/atom-keyboard-localization#12] opened 2015-03-30 08:52 UTC
Hi, first of all, thanks for your plugin, it makes Atom usable for azerty users.
But unfortunately, AltGr is not working in french layout :cry:

**Comment by andischerer** [comment] 2015-03-31 06:48
Could you please provide more information on this issue. Can't reproduce it.
- On which OS are you ?
- Which keymap is activated in the plugin (fr_FR, fr_BE)? You can also check the devtools-console for this.
- Give an example what's not working properly, what prints the keybinding-resolver, which key should be printed ?

**Comment by KabbAmine** [comment] 2015-03-31 09:11
Ok, sorry for not providing those informations from the beginning.
- I'm using Xubuntu 14.04
- Keyboard layout fr_FR.

As an example, AltGr+3 should give `#` but I have `"`, from the keybinding-resolver, AltGr key is not recognized (I have `à` instead)
I can have the desired character using normal Alt, but its not the normal behavior.

Also, I've just noticed today that the same issue occurs with both shift keys, they are not taken account when used in a combination with a number (shift+3==3 but I have `"`).

**Comment by andischerer** [comment] 2015-03-31 09:50
Thanks for your completion. I'll have to check that on my linux-box. I think i know why it's not working.

**Comment by ghivert** [comment] 2015-04-05 23:07
Same here ! Works perfectly on Windows, and non working on OpenSUSE. To be more precise : shift key doesn't work only with the numeric touch (i.e. `&/1`, `é/2`, etc.), but is functionnal with `=/+` or `)/°`. Only with numbers. Same thing for AltGr : `€` via AltGr + e is not a problem, but `#` i s not working. :)

Edit : Strangely, AltGr + < gives `*` and AltGr + Shift + < gives `µ` (on my mapping, it should give `|` and `¦`), same for AltGr + ; or AltGr + : (gives not the good result). The rest works with no problem.

**Comment by andischerer** [comment] 2015-04-06 15:30
Should be fixed in v1.2.0

**Comment by KabbAmine** [comment] 2015-04-07 12:32
Thanks, now AltGr works well for most cases, but some combinations doesn't return the appropriate result.
- AltGr+`²` should return `¬` not `~`.
- AltGr+`&` should return `¹` not `&`.

And as @ghivert said, the `<` key is not recognized at all (Alone or with alt/altGr/shift).

![azerty-fr](https://cloud.githubusercontent.com/assets/5658084/7022843/d92162c4-dd38-11e4-963c-86485f8ef780.jpg)

I've tested all basic fr keys and what above is all what I've found (Maybe should we open a new issue for `<`?).

_P.S: I'm a vim user so Atom is not my primary editor, but I will report all non functional keys when I can._

**Comment by andischerer** [comment] 2015-04-07 13:39
Sorry i missed these 2 (`²` + `&`)  keys. I didnt actually know that there is an AltGr functionality behind these keys (not obvious if you look on the keyboard-layout screenshot). 
It seem to me that the angle brackets issue is linux only. I'll double check that on my linux-box.

No need for a new issue => reopened

Thanks for your support.

**Comment by andischerer** [comment] 2015-04-07 17:15
`AltGr+²` and  `AltGr+&` should be fixed in the next version.

Bad news on the anglebrackets behaviour: The `<>` and the `*µ` key fire exactly the same KeyboardEvent so i cant make a decision to which key i should translate to. This is probably a bug in chromium on linux.

I switched the key translation:
`<` to `<`
`>` to `>`
`AltGr <` to `|`
The `*µ` key has now the same behavior. I think on a programmers keyboard-layout the anglebrackets are more often used as the `*µ` key. And the `*` character could be reached via numpad.

Any objection/thoughts on that ??

**Comment by andischerer** [comment] 2015-04-07 17:19
whoops i forgot about the windows users. I have to do the translation of the anglebrackes in code with an os switch.

**Comment by KabbAmine** [comment] 2015-04-07 19:00
Too bad for the `*` key, a lot of keyboards does not provide numpad keys :confused:  (In some notebooks for example).

But if those keys share the same KeyboardEvent, I don't see other alternative than disabling some of them, and your choice seems to be the best.

**Comment by ghivert** [comment] 2015-04-08 16:17
I'm really often coding on my laptop, and I don't have numpad keys... I imagine that correct the bug in chromium on linux is complicated ? (I don't know dependecy for atom... :))

**Comment by andischerer** [comment] 2015-04-08 18:46
The Atom editor runs on top of atom-shell. Atom-shell is based on io.js and Chromium.

Yesterday i saw the chromium/blink devteam is making progress on the DOM-Level 3 Keyboard-Event implementation (https://code.google.com/p/chromium/issues/detail?id=227231).
I keep my fingers crossed that this implementation lands very soon in atom. It should eliminate all those nasty keyboard-localization issues and suddenly making my package obsolete.  ;-)

**Comment by KabbAmine** [comment] 2015-04-09 16:34
Let all of us keep fingers crossed :smile:

**Comment by KabbAmine** [comment] 2015-07-26 10:13
Looks like #42 solves our problem, check it out.

**Comment by andischerer** [comment] 2015-08-08 12:39
should be fixed in v1.4.7

**Closed as completed by andischerer** 2015-08-08 12:39 UTC

**Comment by KabbAmine** [comment] 2015-08-08 14:56
Confirmed :+1: 
Thanks for your work.
