### ISSUE TITLE
Problem with Atom 1.0.3

### ISSUE THREAD

**Issue by warpdesign** [andischerer/atom-keyboard-localization#44] opened 2015-07-29 08:30 UTC
Atom quietly updated to the latest version today and I noticed that when pressing certain keys, it adds an extra character on the screen.

For example, typing `:` will actually output `:,`

If I disable keyboard-localization it doesn't happen anymore.

I'm using the latest plugin version: 1.4.3, with the french keymap set

**Comment by norbert-berenyi** [comment] 2015-07-29 09:12
Same problem here. I'm useing the Hungarian layout. Double '-' '_', also dots not working.

**Comment by andischerer** [comment] 2015-07-29 09:13
duplicate of #43
Please subscribe there.

**Closed as completed by andischerer** 2015-07-29 09:13 UTC
