### ISSUE TITLE
Two characters when entered only one

### ISSUE THREAD

**Issue by willfri** [andischerer/atom-keyboard-localization#43] opened 2015-07-28 23:21 UTC
When I enter the character `'` it shows me `'?` (two chars).
It worked well as I installed (two days ago) the package but not any more.

I use the "de_DE" keyboard layout at a german keyboard (QWERTZ) with Windows 8.1 (64 Bit).

Sorry for my english but I am from Germany.

**Comment by d-sko** [comment] 2015-07-29 05:52
I can confirm this, same here, some are just duplicated (like e.g. `.` or `!`) and some add another character (e.g. `/` > `/&` or `&` > `&^`). This does not happen for letters and numbers.

(Atom 1.0.3 on Windows 7)

**Comment by LoLei** [comment] 2015-07-29 06:26
Same here too, it seems it is adding the US keys in addition to the localized keys.
Disabling the package solves it, so it definitely comes from here.

Atom version: 1.0.3
OS: Windows  7 64bit
Localization: de_DE

(So weird that today two of my "most used" packages, [ex-mode](https://github.com/lloeki/ex-mode/issues/75) and [keyboard-localization](https://github.com/andischerer/atom-keyboard-localization/issues/43), have a critical error, rendering them unusable. :weary: )

**Comment by slhck** [comment] 2015-07-29 08:15
Same problem, seems to have started when updating Atom to 1.0.3, Windows 7, German keyboard layout.

This makes Atom unusable for me, since the German keyboard layout doesn't work properly without this package (`Alt-Gr` and whatnot).

**Comment by ChowSinWon** [comment] 2015-07-29 08:16
same here since atom update from v1.0.2 to v1.0.3.
OS: Windows 8.1 (64bit)
Localization: de_DE

disabling keypoard-localization package fixes double characters, but of course main purpose of package (for me) was enabling ALT-GR functionality, which won't work without this package.

**Comment by norbert-berenyi** [comment] 2015-07-29 09:14
Same problem here.
OS: Windows 7
Localization: hu_HU

**Comment by warpdesign** [comment] 2015-07-29 09:14
+1 (french keymap).
I have to switch to another editor until this is fixed.

**Comment by LoLei** [comment] 2015-07-29 09:48
So it's confirmed to happen for keymaps other than de_DE too.

**Comment by BlaM** [comment] 2015-07-29 10:19
Just for reference: https://github.com/atom/atom/issues/8135 (same issue, just reported to Atom)

**Comment by andischerer** [comment] 2015-07-29 11:59
I'm on it.

**Comment by andischerer** [comment] 2015-07-29 12:46
Should be fixed in version 1.4.4
If not, please let me know

**Comment by norbert-berenyi** [comment] 2015-07-29 12:48
Works great on hu_HU!

EDIT: Problem: Alt Gr + f ( witch makes '[' ) also triggers Ctrl+f witch is find in current buffer.

**Comment by warpdesign** [comment] 2015-07-29 12:50
I can confirm it also fixes the problem for me (fr_fr).

_Edit_ I went too fast. Double character is indeed fixed, but alt-gr now incorrectly works, as if the plugin wasn't working.

**Comment by slhck** [comment] 2015-07-29 12:51
Does not work on German QWERTZ keyboard (`de_DE`), Win 7, Atom 1.0.3, plugin version 1.4.4.

For example:
- When I press `Alt-Gr` + `Q` I would expect an `@` but it does something weird with the indentation.
- When I press `Alt-Gr` + `ß` I would expect a backslash but I get the current block folded

Not sure in which way German is different there.

**Comment by willfri** [comment] 2015-07-29 12:52
Same issue like @slhck on german keyboard (de_DE).

**Comment by LoLei** [comment] 2015-07-29 12:53
+1 same de_DE issues

It did however fix the adding of additional unlocalized characters.

**Comment by warpdesign** [comment] 2015-07-29 12:54
+1

**Comment by BlaM** [comment] 2015-07-29 12:58
That's actually another problem. Try disabling the "autoflow" package included in Atom.

https://github.com/atom/autoflow/issues/16

**Comment by slhck** [comment] 2015-07-29 13:01
@BlaM Hmm. I can see how that is clashing w.r.t. the keyboard shortcut, thanks.

But given that everything has worked fine until now and the third-party plugin is the "optional" one, overriding the core functionality, I'd rather have this one work than disabling `autoflow`.

Also, it doesn't solve the backslash issue.

**Comment by LoLei** [comment] 2015-07-29 13:02
@BlaM That works for `Alt-Gr` + `Q` (`@`) but not for `Alt-Gr` + `ß` (`\`)

**Comment by willfri** [comment] 2015-07-29 13:03
Can confirm @BlaM. Works after disabling "autoflow".

@LorenzLeitner for me works both when "autoflow" is disabled.

**Comment by norbert-berenyi** [comment] 2015-07-29 13:04
The solution @BlaM suggesting is fixing the `Alt-Gr` + `Q` problem on hu_HU, but `Alt-Gr` + `F` still triggers search alongside the character `[` .

**Comment by warpdesign** [comment] 2015-07-29 13:05
Alt-Gr + ']' still triggers code folding on fr_fr. Disabling autoflow package doesn't help.

**Comment by LoLei** [comment] 2015-07-29 13:06
@willfri Well it types the `\` but it still folds the pane.

Hearing from the others I guess a few additional shortcuts do not work either, with Autoflow disabled.

**Comment by willfri** [comment] 2015-07-29 13:11
@LorenzLeitner When I disable "autoflow" all Alt-Gr shortcuts are working without any side effect.

**Comment by BlaM** [comment] 2015-07-29 13:11
@norbert-berenyi I was just talking about the de_DE problem. That's the only keyboard layout I have ;)

@slhck + @warpdesign + ...
Many still existing problems are caused by other packages that bind to specific keys. AltGr + Q is triggering "Autoflow". An alternative to disabling the built-in package would be to modify the keyboard bindings yourself via File > Open Your Keymap.

@LorenzLeitner
~~"\" works for me. Maybe another package? "ß" is "-" on US kayboards, maybe you can find something on the Keybindings tab in your Settings?~~ (whoops, can't say anything about that, yet. Still on my downgraded version 1.0.2 - maybe that's why it works)

**Comment by LoLei** [comment] 2015-07-29 13:14
@willfri @BlaM Thanks for the help, I will see what I can find.

**Comment by slhck** [comment] 2015-07-29 13:18
Just to remind everyone that the backslash _did_ work before and I didn't install any other packages in between, apart from updating Atom.

I don't see anything else in the keybindings that maps `Ctrl-Alt-ß` or however it is labeled.

**Comment by andischerer** [comment] 2015-07-29 13:21
sorry guys for this too fast fix. 
Could you try v1.4.5 and report back.

**Comment by ChowSinWon** [comment] 2015-07-29 13:24
v1.4.5 looks good.
backslash, @-key and brackets work without side effects for me.
(WIN 8.1 64bit, de_DE)

**Comment by LoLei** [comment] 2015-07-29 13:26
For anyone still having trouble with `\`, this keymap unbinding seemed to fix it for me:

```
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-[': 'unset!'
```

**Comment by andischerer** [comment] 2015-07-29 13:27
autoflow and code folding should not trigger anymore in v 1.4.5

**Comment by slhck** [comment] 2015-07-29 13:29
Working fine now for me as well. Thanks for the quick fixes, @andischerer !

**Comment by willfri** [comment] 2015-07-29 13:30
When "autoflow" is enabled only the `@`-Key is not working correctly. The code shifts to left but the `@` is entered.

EDIT: It works now after restarting Atom. Thank you!

**Comment by LoLei** [comment] 2015-07-29 13:31
Working here (de_DE) with Autflow enabled and no keybindings edited too, thanks!

**Comment by d-sko** [comment] 2015-07-29 13:39
It's working again (de_DE), thank you!

**Comment by BlaM** [comment] 2015-07-29 13:41
Thank You! :+1:

**Comment by norbert-berenyi** [comment] 2015-07-29 13:44
hu_HU is also perfect.

**Comment by andischerer** [comment] 2015-07-29 13:53
there was a minor bug with accent keys e.g. 

```
^ `
```

fixed in 1.4.6 - sorry for version bashing :grin:. 
Thanks for your support :ok_hand:

**Closed as completed by andischerer** 2015-07-29 13:53 UTC

**Comment by k5e** [comment] 2015-07-29 14:24
Big thanks @andischerer!

**Comment by yukulele** [comment] 2015-07-31 14:43
I have also this problem: 
for example I type `-`, i get `-6`

keyboard layout: FR_fr
Atom v1.0.3
keyboard-localization v1.4.6
